backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "properties"
    label: "Properties"
    folder: "properties"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Bedrooms", name: "bedrooms", widget: "number" }
      - { label: "Bathrooms", name: "bathrooms", widget: "number" }
      - label: "Status"
        name: "status"
        widget: "select"
        options: ["For Sale", "For Rent", "Sold"]
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Main Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
